### PR TITLE
Corrected primary key for privilege_rule table (see #57)

### PR DESCRIPTION
**Pull request by cimmanon**
Includes migration script that should be safe to run even if the database has already been updated.

### CODE REVIEW

**Comment by cimmanon** [comment]
I would appreciate it if someone would either close or merge this pull request.

**Comment by sol** [comment]
Travis fails, closing.

**Comment by alpmestan** [comment]
Closing a PR because one little bit of the tests needs to be adapted? Wow. I'll probably stop recommending sproxy.

**Comment by cimmanon** [comment]
@sol Closing this because you blindly trusted your tests does not surprise me one bit.  If Travis is failing, it was failing when I made the branch because it is impossible for changes to SQL files that Sproxy *doesn't even run* to cause a compilation error in Haskell.

**Comment by sol** [comment]
1. My capacity is limited right now, this is why I may not be very responsive.
1. @cimmanon I think I got you wrong, as I understood you either way (that is "applying" or "closing") is fine with you.
1. @cimmanon I didn't mean there is something wrong with your code, only that somebody has to fix the build before I click the merge button.  This is even true if, as in this case, a new version of `hspec` broke the build.
1. In general I think it makes sense if @jekor takes over maintainership of `sproxy`

**Pull request closed without merging**
